#!/bin/sh

trap 'exec /sbin/init' INT EXIT

PATH=/usr/sbin:/usr/bin:/sbin:/bin

mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys
mount -n -t devtmpfs devtmpfs /dev

fail() {
    echo "$1"
    umount -a 2>/dev/null
    poweroff -f
}

if [ ! -e /dev/vdb ]; then
    fail "===> /dev/vdb not found!"
fi;

if [ ! -e /dev/vdc ]; then
    fail "===> /dev/vdc not found!"
fi;


# mount rootfs
mount -n -m -t erofs /dev/vda /mnt/rootfs

# force format vdb
mkfs.btrfs -q -f /dev/vdb
mount -n -m -t btrfs /dev/vdb /mnt/tmpfs

# create overlay by read-only rootfs and read-write tmpfs
mkdir -p /mnt/tmpfs/upperdir
mkdir -p /mnt/tmpfs/workdir
mkdir -p /mnt/overlay
mount -n -t overlay overlay \
    -o lowerdir=/mnt/rootfs,upperdir=/mnt/tmpfs/upperdir,workdir=/mnt/tmpfs/workdir \
    /mnt/overlay

# create data device if not fomatted
data_device="$(blkid /dev/vdc -t TYPE=btrfs || :)"
if [ -z "$data_device" ]; then
	mkfs.btrfs -q -f /dev/vdc
fi

# mount data device to /var/lib/containers
echo "/dev/vdc /var/lib/containers btrfs defaults 0 0" >> /mnt/overlay/etc/fstab

mkdir -p /mnt/overlay/etc/containers
echo "applehv" > /mnt/overlay/etc/containers/podman-machine

vsock_guest_exec :1025 || true

umount -n /dev /sys /proc

exec /bin/busybox switch_root /mnt/overlay "${init:-/sbin/init}"
